# Generated by Django 2.1.7 on 2019-03-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190323_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='staticfiles/books/%Y/%m/%d'),
        ),
    ]
